x = int(input('오징어'))
y = int(input('숫자입력'))
print(f"x==y의 결과값:{x==y}")
print(f"x!=y의 결과값:{x!=y}")
print(f"x>y의 결과값:{x>y}")
print(f"x<y의 결과값:{x<y}")
print(f"x>=y의 결과값:{x>=y}")
print(f"x<=y의 결과값:{x<=y}")