import turtle
a=turtle.Pen()
a.shape('turtle')
a.color('gold')
a.circle(100)
a.right(72)
a.color('silver')
a.shape('circle')
a.circle(100)
a.right(72)
a.color('pink')
a.shape('circle')
a.circle(100)
a.right(72)
a.color('sky blue')
a.shape('circle')
a.circle(100)
a.right(72)
a.color('red')
a.shape('circle')
a.circle(100)
a.right(72)
a.color('blue')
a.shape('circle')
a.circle(100)
a.right(72)
a.color('orange')
a.shape('circle')
a.color('blue')
a.shape('circle')
a.circle(100)
a.right(72)
a.color('goldy')
a.shape('circle')

turtle.exitonclick()